jobs:
  include:
  - language: python
    python:
    - '3.6'
    - '3.7'
    install:
    - pip install -r requirements.txt
    script:
    - export FLASK_APP=sample_backend.py
    - export FLASK_ENV=development
    - flask run
    - pytest -v flask/*_tests.py

  - language: node_js
    node_js:
    - '14.15.4'
    install:
    - npm install 
    - npm install react-bootstrap bootstrap
    - npm install react-bootstrap-range-slider
    - npm install --global yarn
    script:
    - yarn test --watchAll=false 