// Generated by main.pagedraw.json
import React from 'react';
import './index.css';


export default class Index extends React.Component {
  render() {
    return (
      <div className="index-index-2">
          <div className="index-0">
              <div className="index-0-0">
                  <div className="index-rectangle-1">
                      <div className="index-0-0-0-0">
                          <div className="index-your_name_-1">YOUR NAME</div>
                      </div>
                      <div className="index-0-0-0-1">
                          <input type="text" placeholder="eg. Jared" value={this.props.name} onChange={this.props.handleNameChange} className="index-text_input-5" /> 
                      </div>
                  </div>
                  <div className="index-hello_world_-3">
                      { `Hello ${this.props.name || 'world'}!` }
                  </div>
                  <div className="index-rectangle_2" /> 
              </div>
          </div>
          <div className="index-1" /> 
      </div>
    );
  }
};
